name: Build content on upload

on:
  push:
    paths:
      - "incoming/**/*.pdf"
      - "incoming/**/*.PDF"
      - "incoming/**/*.txt"
      - "incoming/**/*.TXT"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check required secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "::error::OPENAI_API_KEY secret is not set."
            exit 1
          fi

      - name: Install dependencies
        run: |
          pip install pymupdf tqdm python-slugify openai

      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4.1
        run: |
          python scripts/generate_content.py

      - name: Commit generated content
        run: |
          git config user.name "auto-content-bot"
          git config user.email "bot@noreply.github.com"
          if [[ -n "$(git status --porcelain content/)" ]]; then
            git add content/
            git commit -m "feat: auto-generated content"
            git push
          else
            echo "No changes to commit; skipping git push."
          fi
